name: link_preview
description: Flutter plugin Rich Link Preview, enabling Android and iOS
  customs component providers like WhatApp, Telegram, Skype, Twitter,
  LinkedIn.
author: Denny Segura <dev.dennysegura@gmail.com>
version: 0.0.1
homepage: https://github.com/devdennysegura/flutter-link-preview

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.0.8

flutter:
  plugin:
    androidPackage: io.flutter.plugins.linkpreview
    pluginClass: LinkPreviewPlugin